import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";


const inter = Inter({
  variable : "--font-inter",
  weight : ['400', '500','600','700','800'],
  subsets : ['latin']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-background-light dark:bg-background-dark`}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
